// https://dailyfantasysports.codes/basics/draftkings-casual-players-contests-introduced/

const EXPERIENCE_LEVELS = Object.freeze({
  NO_LEVEL: 'NO_LEVEL',
  ENTERED_AT_LEAST_500_CONTESTS: 'ENTERED_AT_LEAST_500_CONTESTS',
  ENTERED_AT_LEAST_1000_CONTESTS: 'ENTERED_AT_LEAST_1000_CONTESTS',
  BIG_WIN: 'BIG_WIN',
  ENTERED_AT_LEAST_500_CONTESTS_AND_BIG_WIN: 'ENTERED_AT_LEAST_500_CONTESTS_AND_BIG_WIN',
  ENTERED_AT_LEAST_1000_CONTESTS_AND_BIG_WIN: 'ENTERED_AT_LEAST_1000_CONTESTS_AND_BIG_WIN',
});

const EXPERIENCE_CLASS_NAME_TO_EXPERIENCE_LEVEL = Object.freeze({
  'icon-experienced-user-1': EXPERIENCE_LEVELS.ENTERED_AT_LEAST_500_CONTESTS,
  'icon-experienced-user-2': EXPERIENCE_LEVELS.ENTERED_AT_LEAST_1000_CONTESTS,
  'icon-experienced-user-3': EXPERIENCE_LEVELS.BIG_WIN,
  'icon-experienced-user-4': EXPERIENCE_LEVELS.ENTERED_AT_LEAST_500_CONTESTS_AND_BIG_WIN,
  'icon-experienced-user-5': EXPERIENCE_LEVELS.ENTERED_AT_LEAST_1000_CONTESTS_AND_BIG_WIN,
});

export {
  EXPERIENCE_CLASS_NAME_TO_EXPERIENCE_LEVEL,
  EXPERIENCE_LEVELS,
};
